# Generated by Django 3.2.9 on 2022-03-28 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditapp', '0002_cra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cra',
            name='Clause',
            field=models.CharField(max_length=15),
        ),
    ]
